/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cucumber;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertTrue(1 == 1);
    }
}
